### PR TITLE
Create README.md for the Frontend code.

### PR DESCRIPTION
**Pull request by ren1290**

### CODE REVIEW

**Review by Legus-Yeung — APPROVED** [review]
LGTM! Thanks!

**Comment by kris20012** [comment]
Great start! README has instructions for how to setup the repo locally.

Please also add your basic home page as well as add documentation to the README for how users would be able to test the website locally on computer. For example, under the frontend directory you may want to add a src folder which can have an app folder which can have a pages folder holding your home page. You can have "Hello World" as your home page to keep it simple. Thanks!

**Review by Legus-Yeung — APPROVED** [review]
Its good, thanks for writing up!

**Comment by kris20012** [comment]
Thanks for documenting the steps simply, it will definitely make it easy for the next person!
I think the setup looks good, I believe the .gitignore file may be redundant because of the one at the higher level.

**Pull request merged**
